---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: password-generator-ingress
  namespace: password-generator
spec:
  ingressClassName: "traefik"
  rules:
    - host: password.k8s.tinux-it.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: password-generator
                port:
                  number: 80